### ISSUE TITLE
News feed?

### ISSUE THREAD

**Issue by rollcat** [mason-larobina/factorio#1]
I loved your first post, and I'd love to subscribe to the blog via an RSS/Atom feed.

**Comment by mason-larobina** [comment]
Hi Kamil,

Thanks for reading! The closest I have to feed is the auto-generated GitHub atom link for a repo:

https://github.com/mason-larobina/factorio/commits/master.atom

Should be ~1 commit per post & I'll include entry links in the description.

Regards,

Mason

**Comment by rollcat** [comment]
That should work :)

Thanks & best,
Kamil

**Comment by mason-larobina** [comment]
Awesome! :)
