### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by TomDakan** [mason-larobina/factorio#3]
I don't have an issue, just felt weird sending an email to a stranger about a game. But I wanted to say thank you for sharing a bit about your thought process and designs. I stumbled across them last night as I was thinking about various potential solutions for some problems I've been trying to work through with designing some more complex circuit logic for LTN stations and I think it's going to help me to solve some of these problems. I do a lot more high-level programming and I'm struggling to get my brain around the more analog or possibly Electrical Engineering mindset. Anyway, thank you and I'm glad to see that you're still having fun with Factorio and experimenting with logistics in SE!

**Comment by mason-larobina** [comment]
Glad you enjoyed the posts and thanks for the message :D

If you try out the save or blueprints and have any troubles let me know.
